title: Picasso Painting
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
color_scheme: light
accent_color: blue
header:
  title: Picasso Painting
  has_nav: true
footer:
  content: '&copy; Picasso Painting Company. All rights reserved.'
  # links:
  #   - text: Picasso Painting Comp
  #     url: 'http://www.picassopaitingcompany.com'
  #     new_window: false
  has_social: false
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
